services:
  niryo:
    image: ghcr.io/moralesuji/ir2120_docker/niryo:base
    container_name: niryo-base-compose

    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - QT_X11_NO_MITSHM=1

    network_mode: host

    privileged: true

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/niryo_ws:/home/niryo/niryo_ws


    devices:
      - /dev/dri:/dev/dri

    command: tail -f /dev/null