services:
  app-dev:
    build:
      context: ..
      dockerfile: Dockerfile
      args: 
        ENVIRONMENT: base
    image: ghcr.io/moralesuji/ir2120_docker/niryo:base
    container_name: niryo-base-compose

  app-nvidia:
    build:
      context: ..
      dockerfile: Dockerfile
      args: 
        ENVIRONMENT: nvidia
    image: ghcr.io/moralesuji/ir2120_docker/niryo:nvidia
    container_name: niryo-nvidia-compose