services:
  niryo:
    image: niryo:latest

    environment:
      - DISPLAY=host.docker.internal:0
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - QT_X11_NO_MITSHM=1

    network_mode: host

    privileged: true

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix

    devices:
      - /dev/dri:/dev/dri

    command: tail -f /dev/null